config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'home#index'
  
  resources :conversations, only: [:index, :create]
  resources :messages
  resources :text_messages
  resources :competitions
  resources :listeners, only: [:index, :edit, :update]
  post '/competitions/:id', to: 'competitions#pick_winner', as: 'pick_winner'
  
  get '/mass_messages' => 'messages#get_mass_messages', as: 'get_mass_messages'
  post '/mass_messages' => 'messages#mass_messages', as: 'mass_messages'
end

app/models/message.rb
class Message < ApplicationRecord
  scope :for_number,        -> (number) { where(number: number).by_date }
  scope :by_date,           -> { order(created_at: :desc) }
  scope :recent_by_number,  -> { group(:number).having('created_at = MAX(created_at)') }

  validates :text, presence: true, allow_blank: false
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ApplicationHelper

  def index
    @listeners = Listener.all
    @conversations = Conversation.includes(:messages)
  end

  def show
    @listener = Listener.where(phone_number: params[:id]).first
    @conversation = Conversation.where(sender_id: @listener.id).first
    
    @messages = @conversation.messages.for_number(params[:id]).order("created_at DESC")
    @new_message = @conversation.messages.new(number: params[:id])
  end

  def create
    @listener = Listener.where(phone_number: params[:message][:number]).first
    @conversation = Conversation.where(sender_id: @listener.id).first
    
    message = @conversation.messages.new(clean_params)
    message.inbound = false

    if message.save
      send_cable(message)
      send_sms(message)
    end
  end
  
  def get_mass_messages
  end
  
  def mass_messages
    account_sid = ENV["TWILIO_ACCOUNT_SID"]
    auth_token = ENV["TWILIO_AUTH_TOKEN"]
    @client = Twilio::REST::Client.new account_sid, auth_token
    
    Listener.find_each do |listener|
      @client.messages.create(
        from: ENV["TWILIO_NUMBER"],
        to: listener.phone_number,
        body: params[:mass_message][:text]
      )
    end
    
    redirect_to root_path, notice: "Mass message successfully sent!"
  end

  private

  def clean_params
    params.require(:message).permit(:number, :text)
  end

end

app/views/messages/_detail.html.erb
<div class="content <%= message.inbound ? 'left' : 'right' %> aligned">
  <div class="header">
    <% if message.inbound %>
      <i class='ui icon cloud download'></i> from
    <% else %>
      <i class='ui icon cloud upload'></i> to
    <% end %>
    <%= message.number %>
  </div>
  <div class="meta">
    <span>
      <%= time_ago_in_words message.created_at %> ago
    </span>
  </div>
  <p><%= message.text %></p>
</div>

app/views/messages/_form.html.erb
<div class="ui card">
  <div class="content">
    <%= form_for(@new_message, remote: true, html: { class: 'ui form error' }) do |f| %>
      <%= f.hidden_field :number %>
      
      <div class="field">
        <%= f.text_area :text, rows: 3, class: "form-control" %>
      </div>
      
      <div class="clearfix"></div>
      
      <div class="chat_bottom">
        <%= f.submit 'Send', class: 'pull-right btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<li class="left clearfix <%= message.inbound ? 'admin_chat' : '' %>">
  <div class="chat-body1 clearfix">
    <p>
      <%= message.text %>
    </p>
  </div>
</li>

app/views/messages/create.js.erb
$('textarea').val('');

app/views/messages/get_mass_messages.html.erb
<h1>Send SMS Message To All Listeners</h1>

<%= form_for :mass_message, :url => url_for(:controller => 'messages', :action => 'mass_messages') do |f| %>

  <div class="field">
    <%= f.text_area :text, rows: 3, class: "form-control" %>
  </div>
  
  <div class="clearfix"></div>
  
  <div class="chat_bottom">
    <%= f.submit 'Send', class: 'pull-right btn btn-success' %>
  </div>
<% end %>

app/views/messages/index.html.erb
<div class="main_section">
  <div class="container">
    <div class="chat_container">
      <div class="col-sm-12 chat_sidebar">
        <div class="row">
          <div id="custom-search-input">
            <div class="input-group col-md-12">
              <p class="text-center">Conversations With Listeners - Phone Number is <strong><%= number_to_phone(ENV["TWILIO_NUMBER"]) %></strong></p>
            </div>
            <%= link_to "Send Mass Message", get_mass_messages_path %>
          </div>
          <div class="member_list">
            <ul class="list-unstyled">
              <% @conversations.each do |conversation| %>
                <li class="left clearfix">
                  <div class="chat-body clearfix">
                    <div class="contact_sec">
                      <%= link_to "/messages/#{conversation.sender.phone_number}",  data: { number: conversation.sender.phone_number } do %>
                        <strong class="primary-font"><%= number_to_phone(conversation.sender.phone_number) %></strong>
                      <% end %>
                    </div>
                  </div>
                </li>
              <% end %>
              
            </ul>
          </div>
        </div>
      </div><!--chat_sidebar-->
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="main_section">
  <div class="container">
    <div class="chat_container">
      <div class="col-sm-12 message_section">
        <div class="row">
          <div class="new_message_head">
            <div class="pull-left">
              <button>Messages from <strong><%= number_to_phone(params[:id]) %></strong> to <strong><%= number_to_phone(ENV["TWILIO_NUMBER"]) %></strong></button>
            </div>            
            <div class="pull-right">
              <%= link_to "Back to Conversations", messages_path %>
            </div>
          </div><!--new_message_head-->
          <div class="chat_area">
            <ul class="list-unstyled thread" data-number="<%= params[:id] %>" >
              <%= render @messages %>
            </ul>
          </div><!--chat_area-->
          <div class="message_write">
            <%= render 'form' %>
          </div>
        </div>
      </div><!--message_section-->
    </div>
  </div>
</div>

<br />
<br />

<div class="container bootstrap snippet">
  <div class="panel-body inf-content">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="row">
          <div class="col-md-6">
            <strong>Information for <%= params[:id] %></strong>
          </div>
          <div class="col-md-6">
            <%= link_to "Edit Listener", edit_listener_path(@listener.id) %>
          </div>
        </div>
        <br />

        <div class="table-responsive">
          <table class="table table-condensed table-responsive table-user-information">
            <tbody>
              
              <tr>
                <td>
                  <strong><span class="glyphicon glyphicon-asterisk text-primary"></span> Phone Number</strong>
                </td>
                <td class="text-primary">
                  <%= params[:id] %>
                </td>
              </tr>
              
              <% if @listener.name %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-user text-primary"></span> Name</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.name %>
                  </td>
                </tr>
              <% end %>
              
              <% if @listener.email %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-envelope text-primary"></span> Email</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.email %>
                  </td>
                </tr>
              <% end %>
              
              <% if @listener.address %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-home text-primary"></span> Address</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.city %>
                  </td>
                </tr>
              <% end %>          
              
              <% if @listener.city %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-home text-primary"></span> City</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.city %>
                  </td>
                </tr>
              <% end %>
              
              <% if @listener.state %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-home text-primary"></span> State</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.state %>
                  </td>
                </tr>
              <% end %>
              
              <% if @listener.zip_code %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-home text-primary"></span> Zip Code</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.zip_code %>
                  </td>
                </tr>
              <% end %>       
              
              <% if @listener.age %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-user text-primary"></span> Age</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.age %>
                  </td>
                </tr>
              <% end %>     
              
              <% if @listener.date_of_birth %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-user text-primary"></span> Date of Birth</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.date_of_birth %>
                  </td>
                </tr>
              <% end %>  
              
              <% if @listener.notes %>
                <tr>
                  <td>
                    <strong><span class="glyphicon glyphicon-user text-primary"></span> Notes</strong>
                  </td>
                  <td class="text-primary">
                    <%= @listener.notes %>
                  </td>
                </tr>
              <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>