config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'home#index'
  
  resources :conversations, only: [:index, :create]
  resources :messages
  resources :text_messages
  resources :competitions
  resources :listeners, only: [:index, :edit, :update]
  post '/competitions/:id', to: 'competitions#pick_winner', as: 'pick_winner'
  
  get '/mass_messages' => 'messages#get_mass_messages', as: 'get_mass_messages'
  post '/mass_messages' => 'messages#mass_messages', as: 'mass_messages'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: Listener
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    session[:conversations] ||= []
    
    @listeners = Listener.all
    @conversations = Conversation.includes(:messages).find(session[:conversations])
  end
  
  def create
    @conversation = Conversation.all.order('created_at DESC')
    
    add_to_conversations unless conversated?
    
    respond_to do |format|
      format.js
    end
  end
  
  private
    
    def add_to_conversations
      session[:conversations] ||= []
      session[:conversations] << @conversation.id
    end
    
    def conversated?
      session[:conversations].include?(@conversation.id)
    end
end

app/views/conversations/_conversation.html.erb
<li>
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-heading">
      <%= link_to conversation.sender.phone_number, '', class: 'toggle-window' %>
      <%= link_to "x", '', class: "btn btn-default btn-xs pull-right" %>
    </div>

    <div class="panel-body" style="display: none;">
      <div class="messages-list">
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages %>
        </ul>
      </div>
    </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, listener: listener %>
<% end %>

app/views/conversations/create.js.erb
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
 
if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}
 
conversation.find('.panel-body').show();
 
var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/conversations/index.html.erb
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation %>
      <% end %>
    </ul>
  </div>
 
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Listener Phone Number list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @listeners.each do |listener| %>
            <li><%= link_to listener.phone_number, conversations_path(listener_id: listener), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>