config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'home#index'
  
  resources :conversations, only: [:index, :create]
  resources :messages
  resources :text_messages
  resources :competitions
  resources :listeners, only: [:index, :edit, :update]
  post '/competitions/:id', to: 'competitions#pick_winner', as: 'pick_winner'
  
  get '/mass_messages' => 'messages#get_mass_messages', as: 'get_mass_messages'
  post '/mass_messages' => 'messages#mass_messages', as: 'mass_messages'
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :competitors
  
  def self.not_expired
      where('end_date >= ?', Date.current)
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :pick_winner]
  skip_before_action :verify_authenticity_token, only: [:incoming_sms]
  
  def index
    @competitions = Competition.not_expired
  end
  
  def show
  end
  
  def new
    @competition = Competition.new
  end
  
  def create
    @competition = Competition.new(competition_params)
    @competition.keyword.downcase!
    
    if @competition.save
      redirect_to competition_path(@competition), notice: 'Your competition was successfully created!'
    else
      render :edit, notice: 'There was an error processing your request!'
    end
  end
  
  def edit
  end
  
  def update
    if @competition.update(competition_params)
      redirect_to @competition, notice: 'Your competition was successfully updated!'
    else
      render :edit, notice: 'There was an error processing your request!'
    end
  end
  
  # It might need a refactor
  def pick_winner
    if @competition.winner
      redirect_to competition_path(@competition)
    else
      if not @competition.competitors.count == 0
        
        if @competition.category == 'one_random'
          picked_winner = @competition.competitors.order("RANDOM()").first.phone_number
          @competition.winner = picked_winner
          @competition.save
          
          # Send SMS to winner
          boot_twilio
          sms = @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: picked_winner,
            body: "Hello! You've won our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
          message = Message.create!(
            number: picked_winner,
            text: "Hello! You've won our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )
          
          redirect_to competition_path(@competition), notice: 'Successfully Picked a Winner! -- please check the messages tab in order to get in contact with the winner'
        
        elsif @competition.category == 'first_listener'
          picked_winner = @competition.competitors.first.phone_number
          @competition.winner = picked_winner
          @competition.save
          
          # Send SMS to winner
          boot_twilio
          sms = @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: picked_winner,
            body: "Hello! You've won our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
          message = Message.create!(
            number: picked_winner,
            text: "Hello! You've won our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )
          
          redirect_to competition_path(@competition), notice: 'Successfully Picked a Winner! -- please check the messages tab in order to get in contact with the winner'
        
        elsif @competition.category == 'last_listener'
          picked_winner = @competition.competitors.last.phone_number
          @competition.winner = picked_winner
          @competition.save
          
          # Send SMS to winner
          boot_twilio
          sms = @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: picked_winner,
            body: "Hello! You've won our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
          message = Message.create!(
            number: picked_winner,
            text: "Hello! You've won our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )
          
          redirect_to competition_path(@competition), notice: 'Successfully Picked a Winner! -- please check the messages tab in order to get in contact with the winner'
        
        elsif @competition.category == 'two_random'
          first_winner = @competition.competitors.order("RANDOM()").first.phone_number
          second_winner = @competition.competitors.order("RANDOM()").first.phone_number
          @competition.winner = first_winner
          @competition.second_winner = second_winner
          @competition.save
          
          # Send SMS to winners
          boot_twilio
          
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: first_winner,
            body: "Hello! You are the first winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
           
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: second_winner,
            body: "Hello! You are the second winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
          Message.create!(
            number: first_winner,
            text: "Hello! You are the first winner of our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )    
          
          Message.create!(
            number: second_winner,
            text: "Hello! You are the second winner of our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )
          
          redirect_to competition_path(@competition), notice: 'Successfully Picked Winners! -- please check the messages tab in order to get in contact with the winner'
                
        elsif @competition.category == 'three_random'
          first_winner = @competition.competitors.order("RANDOM()").first.phone_number
          second_winner = @competition.competitors.order("RANDOM()").first.phone_number
          third_winner = @competition.competitors.order("RANDOM()").first.phone_number
          @competition.winner = first_winner
          @competition.second_winner = second_winner
          @competition.third_winner = third_winner
          @competition.save
          
          # Send SMS to winners
          boot_twilio
          
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: first_winner,
            body: "Hello! You are the first winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
           
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: second_winner,
            body: "Hello! You are the second winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )          
          
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: third_winner,
            body: "Hello! You are the third winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
          Message.create!(
            number: first_winner,
            text: "Hello! You are the first winner of our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )    
          
          Message.create!(
            number: second_winner,
            text: "Hello! You are the second winner of our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )      
          
          Message.create!(
            number: third_winner,
            text: "Hello! You are the third winner of our competition - #{@competition.title} - we will contact you soon for your prize!",
            inbound: false
          )
          
          redirect_to competition_path(@competition), notice: 'Successfully Picked Winners! -- please check the messages tab in order to get in contact with the winner'
                        
        elsif @competition.category == 'four_random'
          first_winner = @competition.competitors.order("RANDOM()").first.phone_number
          second_winner = @competition.competitors.order("RANDOM()").first.phone_number
          third_winner = @competition.competitors.order("RANDOM()").first.phone_number
          fourth_winner = @competition.competitors.order("RANDOM()").first.phone_number
          @competition.winner = first_winner
          @competition.second_winner = second_winner
          @competition.third_winner = third_winner
          @competition.fourth_winner = fourth_winner
          @competition.save
          
          # Send SMS to winners
          boot_twilio
          
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: first_winner,
            body: "Hello! You are the first winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
           
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: second_winner,
            body: "Hello! You are the second winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )          
          
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: third_winner,
            body: "Hello! You are the third winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )     
          
          @client.messages.create(
            from: ENV["TWILIO_NUMBER"],
            to: fourth_winner,
            body: "Hello! You are the fourth winner of our competition - #{@competition.title} - we will contact you soon for your prize!"
          )
          
          Message.create!(
            number: first_winner,
            text: "Hello! You are the first winner of our competition - #{@competition.title} - we will contact you soon for your prize!",

app/views/competitions/_competition.html.erb
<tr>
  <td><%= competition.title %></td>
  <td><%= competition.keyword %></td>
  <td><%= competition.competitors.count %></td>
  <td>
    <%= link_to "Details", competition, :class => "btn btn-default btn-block" %>
  </td>
</tr>

app/views/competitions/_form.html.erb
<%= form_for @competition do |f| %>
  <label>Title</label>
  <%= f.text_field :title, placeholder: "Competition Title" %>
  <br />
  <label>Keyword</label>
  <%= f.text_field :keyword, placeholder: "Competition Keyword" %>
  <br />
  <p>Note: Please choose a Winning Schema or a Nth Listener and NOT both!</p>
  
  <label>Winning Schema</label>
  <%= f.select :category, grouped_options_for_select(
    'Default' => [
                  ['One Winner','one_random']
                 ],
                 
    'Multiple Winners' => [ 
                              ['Two Winners', 'two_random'],
                              ['Three Winners', 'three_random'],
                              ['Four Winners', 'four_random'],
                              ['Five Winners', 'five_random']
                             ],
                        
    'First or Last' => [
                        ['First Listener', 'first_listener'],
                        ['Last Listener', 'last_listener']
                       ]
          
  ), {prompt: 'None'} %>
  
  <br></br>
  <label>Nth Listener</label>
  <%= f.select :nth_listener, (1..200), {prompt: 'None'} %>
  
  <br></br>
  
  <label>Start Date</label>
  <%= f.date_select(:start_date, prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, placeholder: "Competition Start Date") %>  
  
  <br></br>
  
  <label>End Date</label>
  <%= f.date_select(:end_date, prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, placeholder: "Competition End Date") %>
  
  <br></br>
  <%= f.submit "Save" %>
<% end %>

app/views/competitions/edit.html.erb
<%= render partial: 'form', locals: { source: 'edit' } %>

app/views/competitions/index.html.erb
<h3>Competitions</h3>
<div class="container">
  <div class="table-responsive">
    <table class="table table-bordered text-center">
      <thead>
        <tr>
          <th>Title</th>
          <th>Keyword</th>
          <th>Listener Count</th>
          <th><%= link_to "Add Competition", new_competition_path, :class => "btn btn-default btn-block" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @competitions %>
      </tbody>
    </table>
  </div>
</div>

app/views/competitions/new.html.erb
<%= render partial: 'form', locals: { source: 'edit' } %>

app/views/competitions/show.html.erb
<h1><%= @competition.title %></h1>
<h2><%= @competition.keyword %></h2>
<h3><%= @competition.category %></h3>

<% if @competition.winner %>
  <h3><%= @competition.winner %></h3>
<% else %>
  <%= link_to 'Pick Winner', pick_winner_path(@competition), method: :post %>
<% end %>